<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BNGLT-9V9P882" name="com.qa.testcases.CreateSTPPagetest" tests="2" failures="0" timestamp="26 Dec 2018 09:56:15 GMT" time="36.416" errors="1">
  <testcase name="HelpTextValidation" time="36.381" classname="com.qa.testcases.CreateSTPPagetest"/>
  <testcase name="MandatoryFieldValidation" time="0.035" classname="com.qa.testcases.CreateSTPPagetest">
    <error type="java.io.FileNotFoundException" message=".\src\main.java\com.qa.TestData\testData.xlsx (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: .\src\main.java\com.qa.TestData\testData.xlsx (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.qa.DataDriven.ExcelUtility.getCellData(ExcelUtility.java:18)
at com.qa.pages.CreateSTPPage.EnterMandatoryFields(CreateSTPPage.java:201)
at com.qa.testcases.CreateSTPPagetest.MandatoryFieldValidation(CreateSTPPagetest.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- MandatoryFieldValidation -->
</testsuite> <!-- com.qa.testcases.CreateSTPPagetest -->
